### ISSUE TITLE
Radium accessing void voxel. (Startup crash)

### ISSUE THREAD

**Issue by border999** [Asek3/Radium#27]
[latest.log](https://github.com/Asek3/Radium/files/8550373/latest.log)
[debug.log](https://github.com/Asek3/Radium/files/8550374/debug.log)

**Comment by brisingraerowing** [comment]
Do you have Oculus? It breaks things currently.

**Comment by aking4125** [comment]
Looking at the Log file. You have a lot of mods for 1.18.1 but you're running forge for 1.18.2. You'll need to download the 1.18.2 versions of the mods. Try updating as many as possible then see if the error persist.

Most mods for 1.18.1 doesn't work for 1.18.2 unless stated otherwise. Make sure when searching for mods on Curseforge to use the 1.18.2 tag and double check each one.

**Comment by MadProbe** [comment]
To mitigate this error you can disable the mixins that cause the crash in radium's config with `mixin.block=false`.
Also you can test to find out more precise solution as only one or two of them may cause crashes.

**Comment by MadProbe** [comment]
Update: I've tested the config options and fount out that you may disable only `mixin.shapes.shape_merging` and `mixin.shapes.specialized_shapes` config options

**Comment by brisingraerowing** [comment]
This issue pops up when there's a dependency version issue and Forge tries to show the Dependency error screen. If all dependencies are satisfied, the crash does not occur. I'm not sure *why* showing the Dependency error screen crashes, but it does.
